on:
  push:
    branches:
      - master
      
name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Set environmental variables
        run: echo '::set-env name=RELEASE_TAG::0.9.1'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
             python -m pip install --upgrade pip
             python -m pip install sphinx==1.8.0
             python -m pip install sphinx_rtd_theme
             python -m pip install sphinxcontrib-matlabdomain
             python -m pip install sphinxcontrib-httpdomain
             sudo apt install texlive-extra-utils
             sudo apt-get install texlive-latex-extra
      - name: Build documentation
        run: |
             cd docsrc
             sphinx-build -E -b html ./source ../docs
             cd ..
      - name: Package release files
        run: | 
          zip -r DeerLab_${{ env.RELEASE_TAG }}.zip ./functions ./examples ./LICENSE ./docs ./README.md
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}
          body: |
            Changes in this Release:
          draft: false
          prerelease: true
      - name: Upload packaged release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'DeerLab_${{ env.RELEASE_TAG }}.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ env.RELEASE_TAG }}
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Build webpage
        if: success()
        run: |
            cd build
            python -m multiversedocs
            cd ..
      
      - name: Deploy to GH-Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./multidocs
